# **PROGRAM - 2**

## **AIM:**

Matrix operations (using vectorization) and transformation using python and SVD using Python.




In [ ]:
import numpy as pd

In [ ]:
n=[1,2,3,4,5]
print (n)

[1, 2, 3, 4, 5]


In [ ]:
pd.array(n)

array([1, 2, 3, 4, 5])

In [ ]:
m=[[1,2,3],[4,5,6],[7,8,9]]
pd.array(m)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
pd.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
pd.arange(0,14,3)

array([ 0,  3,  6,  9, 12])

In [ ]:
pd.zeros(3)


array([0., 0., 0.])

In [ ]:
pd.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
pd.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
pd.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
pd.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
pd.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [ ]:
pd.linspace(1,6,3)

array([1. , 3.5, 6. ])

In [ ]:
pd.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [ ]:
pd.random.rand(5)

array([0.36673517, 0.52038518, 0.8821126 , 0.49032897, 0.78885939])

In [ ]:
pd.random.rand(2)

array([0.59655309, 0.78540801])

In [ ]:
pd.random.rand(2,2)

array([[0.00456417, 0.19040905],
       [0.88668811, 0.01155942]])

In [ ]:
pd.random.randn(5)

array([-0.7543355 , -0.02772456, -1.02653437,  0.82245293, -1.6574864 ])

In [ ]:
pd.random.randint(1,10)

5

In [ ]:
pd.random.randint(1,100,10)

array([58, 59, 35, 19, 85, 91, 28, 32, 30, 70])

In [ ]:
arr=pd.arange(25)

In [ ]:
pd.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr=pd.random.randint(0,25,5)

In [ ]:
ranarr

array([16, 11,  8, 21,  6])

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr.max()

21

In [ ]:
ranarr.min()

6

In [ ]:
ranarr.argmax()

3

In [ ]:
ranarr.argmin()

4

In [ ]:
arr.shape

(25,)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr[5]

5

In [ ]:
arr[6]

6

In [ ]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [ ]:
arr[1:6]=50

In [ ]:
arr

array([ 0, 50, 50, 50, 50, 50,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.reshape(5,5)

array([[ 0, 50, 50, 50, 50],
       [50,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr[1:5][3:5]=0

In [ ]:
arr

array([ 0, 50, 50, 50,  0, 50,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr_copy=arr.copy()

In [ ]:
arr

array([ 0, 50, 50, 50,  0, 50,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
slice_of_arr=arr[0:6]

In [ ]:
arr

array([ 0, 50, 50, 50,  0, 50,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
A=pd.array([[5,10,15],[20,25,30],[35,40,45]])
A

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
A[1:,:2]

array([[20, 25],
       [35, 40]])

In [ ]:
A[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
A>5

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
A<5

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
A>10

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
A<0

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
true=A>5

In [ ]:
A[true]

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
import numpy as pd

In [ ]:
pd.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a=pd.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b=pd.arange(10,20)

In [ ]:
c=pd.add(a,b)

In [ ]:
c

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
c=pd.subtract(a,b)

In [ ]:
c

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [ ]:
c=pd.subtract(b,a)
c

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [ ]:
c=pd.multiply(a,b)
c

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [ ]:
c=pd.divide(a,b)
c

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [ ]:
a+b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
a-b

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [ ]:
a*b

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [ ]:
a/b 
a/b

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [ ]:
a/a

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1/a

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
a/0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

SVD:

In [ ]:
import numpy as np
A = np.arange(0,25)
from scipy.linalg import svd

In [ ]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
a = np.arange(1,19).reshape(6,3)

In [ ]:
U, s, VT = svd(a)

In [ ]:
U

array([[-0.07736219,  0.71960032, -0.09075777, -0.25083666, -0.45979172,
        -0.4400296 ],
       [-0.19033085,  0.50893247,  0.58409372,  0.4022013 ,  0.06897105,
         0.44392965],
       [-0.3032995 ,  0.29826463, -0.34118019, -0.54123699,  0.50890998,
         0.38822268],
       [-0.41626816,  0.08759679, -0.61888418,  0.65636038,  0.03282454,
        -0.06437079],
       [-0.52923682, -0.12307105,  0.37872289, -0.04363171,  0.43069535,
        -0.61149707],
       [-0.64220548, -0.33373889,  0.08800553, -0.22285632, -0.58160921,
         0.28374512]])

In [ ]:
s

array([4.58945322e+01, 1.64070530e+00, 1.74146424e-15])

In [ ]:
VT

array([[-0.52903535, -0.57607152, -0.62310769],
       [-0.74394551, -0.03840487,  0.66713577],
       [ 0.40824829, -0.81649658,  0.40824829]])

In [ ]:
U, s, VT = svd(a,full_matrices=True)

In [ ]:
U

array([[-0.07736219,  0.71960032, -0.09075777, -0.25083666, -0.45979172,
        -0.4400296 ],
       [-0.19033085,  0.50893247,  0.58409372,  0.4022013 ,  0.06897105,
         0.44392965],
       [-0.3032995 ,  0.29826463, -0.34118019, -0.54123699,  0.50890998,
         0.38822268],
       [-0.41626816,  0.08759679, -0.61888418,  0.65636038,  0.03282454,
        -0.06437079],
       [-0.52923682, -0.12307105,  0.37872289, -0.04363171,  0.43069535,
        -0.61149707],
       [-0.64220548, -0.33373889,  0.08800553, -0.22285632, -0.58160921,
         0.28374512]])

In [ ]:
U, s, VT = svd(a,full_matrices=False)

In [ ]:
U

array([[-0.07736219,  0.71960032, -0.09075777],
       [-0.19033085,  0.50893247,  0.58409372],
       [-0.3032995 ,  0.29826463, -0.34118019],
       [-0.41626816,  0.08759679, -0.61888418],
       [-0.52923682, -0.12307105,  0.37872289],
       [-0.64220548, -0.33373889,  0.08800553]])

In [ ]:
from numpy import diag
from numpy import dot

In [ ]:
a= (U @ np.diag(s) @ VT)

In [ ]:
a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.]])

## **RESULT:**

The program executedsuccessfully and obtained the output