**PROGRAM NO-2**

**Aim:** Matrix operations (using vectorization) and transformation using python and SVD 
using Python. 

In [ ]:
import numpy as np

In [ ]:
a = np.zeros(10)

In [ ]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
a = np.ones(10)

In [ ]:
a*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
a =np.arange(10,51)

In [ ]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
b = np.arange(10,51,2)

In [ ]:
b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
a = np.arange(0,9)

In [ ]:
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a = np.array(a)

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(1)

array([0.58625916])

Use numpy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
a = np.random.randn(25)

In [ ]:
a

array([-0.04896616, -0.8041291 ,  1.13550601, -0.53619693,  2.69545043,
       -0.48403258, -0.69521474, -1.50046868, -1.46007021,  1.12750033,
        0.12596504,  0.40128316,  2.26360832,  0.10771633,  0.15204888,
       -0.03720986,  0.4573639 , -1.33667719,  0.02730499, -1.07894103,
       -0.01669391, -0.5611958 ,  0.43010856, -1.42591487,  1.77139352])

In [ ]:
a = np.random.randn(5,5)

In [ ]:
a

array([[ 0.29482346, -0.80666764,  1.79146308,  1.39839   , -0.86338596],
       [ 1.36779522, -0.29962507,  0.40596963, -0.29847113, -2.63526737],
       [-1.6010666 , -0.63444688, -1.22025455, -0.69600626, -1.63989681],
       [ 0.54234526,  1.70864562, -1.46383217,  0.47120988,  0.4767304 ],
       [-0.32111072,  1.07868078, -3.085043  , -0.82972413,  1.0549771 ]])

create the following matrix the number should be ranging between 0 and 1

In [ ]:
np.linspace(0,100,1)

array([0.])

In [ ]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [ ]:
a = np.arange(1,100,1)

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
a/100

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99])

create an array of 20 lineraly spaced points between 0 and 1


In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
a = np.arange(1,26).reshape(5,5)

In [ ]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
a[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
a[3:4,4:]

array([[20]])

In [ ]:
a[3,4]

20

In [ ]:
a[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
a[4:,0:]

array([[21, 22, 23, 24, 25]])

In [ ]:
a[3:,0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

get the sum of all values in the matrix

create the following matrix the number should be ranging between 0 and 1

In [ ]:
np.linspace(0,100,1)

array([0.])

In [ ]:
a.sum()

325

In [ ]:
a.std()

7.211102550927978

In [ ]:
import numpy as np

In [ ]:
A = np.arange(0,25)

In [ ]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

SVD

In [ ]:
from scipy.linalg import svd

In [ ]:
a = np.arange(1,19).reshape(6,3)

In [ ]:
U, s, VT = svd(a)

In [ ]:
U

array([[-0.07736219,  0.71960032, -0.09075777, -0.25083666, -0.45979172,
        -0.4400296 ],
       [-0.19033085,  0.50893247,  0.58409372,  0.4022013 ,  0.06897105,
         0.44392965],
       [-0.3032995 ,  0.29826463, -0.34118019, -0.54123699,  0.50890998,
         0.38822268],
       [-0.41626816,  0.08759679, -0.61888418,  0.65636038,  0.03282454,
        -0.06437079],
       [-0.52923682, -0.12307105,  0.37872289, -0.04363171,  0.43069535,
        -0.61149707],
       [-0.64220548, -0.33373889,  0.08800553, -0.22285632, -0.58160921,
         0.28374512]])

In [ ]:
s

array([4.58945322e+01, 1.64070530e+00, 1.74146424e-15])

In [ ]:
VT

array([[-0.52903535, -0.57607152, -0.62310769],
       [-0.74394551, -0.03840487,  0.66713577],
       [ 0.40824829, -0.81649658,  0.40824829]])

In [ ]:
U, s, VT = svd(a,full_matrices=True)

In [ ]:
U

array([[-0.07736219,  0.71960032, -0.09075777, -0.25083666, -0.45979172,
        -0.4400296 ],
       [-0.19033085,  0.50893247,  0.58409372,  0.4022013 ,  0.06897105,
         0.44392965],
       [-0.3032995 ,  0.29826463, -0.34118019, -0.54123699,  0.50890998,
         0.38822268],
       [-0.41626816,  0.08759679, -0.61888418,  0.65636038,  0.03282454,
        -0.06437079],
       [-0.52923682, -0.12307105,  0.37872289, -0.04363171,  0.43069535,
        -0.61149707],
       [-0.64220548, -0.33373889,  0.08800553, -0.22285632, -0.58160921,
         0.28374512]])

In [ ]:
U, s, VT = svd(a,full_matrices=False)

In [ ]:
U

array([[-0.07736219,  0.71960032, -0.09075777],
       [-0.19033085,  0.50893247,  0.58409372],
       [-0.3032995 ,  0.29826463, -0.34118019],
       [-0.41626816,  0.08759679, -0.61888418],
       [-0.52923682, -0.12307105,  0.37872289],
       [-0.64220548, -0.33373889,  0.08800553]])

In [ ]:
from numpy import diag

In [ ]:
from numpy import dot

In [ ]:
a= (U @ np.diag(s) @ VT)

In [ ]:
a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.]])

**Result:** The program is executed successfully and obtained the output.